
set(REQUIRED_LIBS Core Network)
find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS ${REQUIRED_COMPONENTS})

message(STATUS "QT_VERSION_MAJOR:${QT_VERSION_MAJOR}")
# find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Core Network)

foreach (QT_LIB ${REQUIRED_LIBS})
     list(APPEND REQUIRED_LIBS_QUALIFIED "Qt${QT_VERSION_MAJOR}::${QT_LIB}")
endforeach (QT_LIB)

message(STATUS "REQUIRED_LIBS_QUALIFIED:${REQUIRED_LIBS_QUALIFIED}")
